### ISSUE TITLE
waypoint beacon stuck in world

### ISSUE THREAD

**Issue by willrun4fun** [rfresh2/XaeroPlus#46] opened 2023-08-19 18:28 UTC
I have a waypoint I removed but the rendered beacon is still present in the world and I don't know how to get rid of it.
1.20.1 Fabric.

**Comment by rfresh2** [comment] 2023-08-19 18:52
Check that you are on the latest XaeroPlus version

A similar bug to this was fixed in July https://github.com/rfresh2/XaeroPlus/commit/6aa488773b9e245dde1140677f549dfdc0ce2723

**Comment by willrun4fun** [comment] 2023-08-19 20:06
I am.  I did have the mod removed for a while when it had the bad fps drops in caves.  Even with xaero plus removed the beacon was still there.  I deleted the waypoint then hoping that would clear it and it did not.  I then later reinstalled it all latest versions and that particular beacon is still there.

**Comment by rfresh2** [comment] 2023-08-19 20:18
if XaeroPlus is removed and your unexpected beacon was still present that means your issue is being caused by another mod.

I'm unable to replicate your problem, all waypoint beacons are removed when waypoints are deleted for me.

**Comment by willrun4fun** [comment] 2023-08-19 21:20
I feel like a goof.  FTB Chunks is also loaded for claims, but I don't use it's map.  Well It had mapped a death location automatically.  Sorry for being a nuisance.

**Closed as completed** 2023-08-19 21:33 UTC
