### ISSUE TITLE
Incompatibility with earthhack 1.8.5

### ISSUE THREAD

**Issue by Baitinq** [rfresh2/XaeroPlus#2] opened 2023-01-24 15:34 UTC
Hi!

I'm getting a crash when using this mod alongside earthhack 1.8.5 (https://github.com/3arthqu4ke/3arthh4ck/releases/tag/1.8.5)

I attach the crash log: https://pastebin.com/ivpLN934

Thank you for your help and for this awesome mod :)

**Comment by rfresh2** [comment] 2023-01-29 23:07
Should be resolved in version 62. 

https://github.com/rfresh2/XaeroPlus/commit/6f0a566f22c80b0876ce00a62a5a704c20ae10c0

Is caused by mod load order issue due to Mixin 0.8.5 requirement. 

Another possible fix: rename `xaeroplus-XX.jar` to `0xaeroplus-XX.jar` in your mods folder.

MC mods are loaded in alphabetical order so this makes XaeroPlus load first.

**Closed as completed by rfresh2** 2023-01-29 23:07 UTC
