### ISSUE TITLE
Crash render Icon Xaero ResourcePack 1.19.2 

### ISSUE THREAD

**Issue by Wolfcvz** [rfresh2/XaeroPlus#157] opened 2024-08-25 02:52 UTC
[crash-2024-08-24_19.43.34-client.txt](https://github.com/user-attachments/files/16738811/crash-2024-08-24_19.43.34-client.txt)

**Comment by rfresh2** [comment] 2024-08-25 03:09
Need the full `latest.log` in `.minecraft/logs` from when it crashed

**Comment by rfresh2** [comment] 2024-08-25 03:21
just looking at it though i'm pretty sure the cause is not related to XaeroPlus

what you should do:
1. remove XaeroPlus
2. reproduce the same crash again
3. create an issue and post your new crash report to https://legacy.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues

**Comment by rfresh2** [comment] 2024-09-02 05:52
looks like you or another person created an issue on xaero's minimap: https://legacy.curseforge.com/minecraft/mc-mods/xaeros-minimap/issues/1488

and looks like xaero confirmed a fix is coming soon

so im just gonna close this here on my github

**Closed as completed by rfresh2** 2024-09-02 05:52 UTC
