### ISSUE TITLE
minimap is not showing with fps limiter option on in 1.19.2 forge

### ISSUE THREAD

**Issue by loti1234** [rfresh2/XaeroPlus#153] opened 2024-07-31 12:02 UTC
without option enabled: 
![image](https://github.com/user-attachments/assets/ea1b4272-69e5-4b01-97af-e1768d51d35a)

with option enabled: 
![image](https://github.com/user-attachments/assets/e9c1ebc6-582d-4cd0-9bba-3e7ded55d04a)

and yes i did try without shader tho the issue still persists

**Comment by rfresh2** [comment] 2024-07-31 17:04
Need more info about what other mods you have installed and your video settings

might be easiest to send me your latest.log (`.minecraft/logs/latest.log`)

**Comment by loti1234** [comment] 2024-07-31 21:41
here's the log

[latest.log](https://github.com/user-attachments/files/16447424/latest.log)

**Comment by rfresh2** [comment] 2024-07-31 21:46
ok yeah that is over 200 mods i don't think ill be able to download them individually and find which one is causing the compat issue easily

but anyway i am pretty sure it is a mod compat issue, which you could easily test for yourself if you remove other mods besides xaero's

**Comment by loti1234** [comment] 2024-08-03 12:30
im gonna post the modpack here and test if xaeroplus fps limiter has issues again
[Omen's Quest.zip](https://github.com/user-attachments/files/16480616/Omen.s.Quest.zip)

btw xaero fps limiter did work before so some mod does not like the workaround ARM JVM for some reason

**Comment by loti1234** [comment] 2024-08-03 12:45
wait shit whoops i sent the modpack with the downgraded one and not the newest one which's causing issues
when u get the modpack update xaeroplus

**Comment by loti1234** [comment] 2024-08-03 20:18
ok so i know whats causing issues, its this mod https://www.curseforge.com/minecraft/mc-mods/the-intruder
xaero with fps limiter while using intruder mod:
![image](https://github.com/user-attachments/assets/264a68b3-37eb-4506-bcd6-25d435fad7c7)

xaero without fps limiter while using intruder mod:
![image](https://github.com/user-attachments/assets/f0754d0c-7025-4368-ba23-465bc68789a9)

[latest.log](https://github.com/user-attachments/files/16482779/latest.log)

**Comment by rfresh2** [comment] 2024-08-08 22:48
unable to reproduce still, must be related to other or more mods

![explorer_GzYUTs9cBB](https://github.com/user-attachments/assets/059e40ef-6f62-4eb0-8517-1b566a4935af)

**Comment by Tgaisen** [comment] 2024-08-09 13:47
I encountered the same issue on Simply Optimized Modpack 1.21-4.3. I only added the WorldMap 1.38.8, Minimap 24.2.1, and XaeroPlus 2.21.1 mods, and then activated the FPS limiter. After that, the minimap stopped displaying. However, when I downgraded XaeroPlus to version 2.19, the minimap displayed correctly.
Here are the logs:
[latest.log](https://github.com/user-attachments/files/16561975/latest.log)

**Comment by rfresh2** [comment] 2024-08-10 04:34
i think i found the issue, related to the MC video setting, GUI Scale, being set to Auto

meaning its unrelated to mod conflicts

you can test the prerelease CI builds:

[Forge 1.19.2](https://nightly.link/rfresh2/XaeroPlus/actions/runs/10328873320/XaeroPlus-2.22%2Bforge-1.19.2-WM1.38.8-MM24.2.0.zip)
[Fabric 1.21](https://nightly.link/rfresh2/XaeroPlus/actions/runs/10328876726/XaeroPlus-2.22%2Bfabric-1.21-WM1.38.8-MM24.2.1.zip)
[or all versions from github actions artifacts](https://github.com/rfresh2/XaeroPlus/actions)

**Comment by Tgaisen** [comment] 2024-08-10 04:54
This version works fine, thanks.

**Comment by Robynstar** [comment] 2024-08-10 09:34
I was having the same issue! Then I went into the Options and set the GUI Scale to something other than Auto and ta-da the minimap is back! So I'd say your guess is correct :)

**Comment by rfresh2** [comment] 2024-08-14 21:03
fixed in 2.22 https://github.com/rfresh2/XaeroPlus/releases/tag/2.22

**Closed as completed by rfresh2** 2024-08-14 21:03 UTC
