### ISSUE TITLE
Create world crash

### ISSUE THREAD

**Issue by al-wei** [rfresh2/XaeroPlus#65] opened 2023-10-01 13:28 UTC
1.12.2 Crash
XaeroPlus-Forge-1.12.2-150-WM1.34.1-MM23.8.0
BetterPvP_23.8.0_Forge_1.12
XaerosWorldMap_1.34.1_Forge_1.12
https://mclo.gs/qmQ3xYj

**Comment by rfresh2** [comment] 2023-10-01 16:42
1. Does it still occur with only xaero mods installed?
i.e. this list of mods you provided:
```
XaeroPlus-Forge-1.12.2-150-WM1.34.1-MM23.8.0
BetterPvP_23.8.0_Forge_1.12
XaerosWorldMap_1.34.1_Forge_1.12
```

I'm unable to reproduce it with only those. So its likely a compatibility issue with something on your (large) mods list. 

2. Do you have a link to the modpack you're using?
3. Please link me the entire latest.log during the crash instead of just the crash log

**Comment by magcicada** [comment] 2023-10-06 09:29
[crash-2023-10-06_17.24.48-client.txt](https://github.com/rfresh2/XaeroPlus/files/12829344/crash-2023-10-06_17.24.48-client.txt)
[latest.log](https://github.com/rfresh2/XaeroPlus/files/12829345/latest.log)
The mods which installed can be found in the crash report

**Comment by magcicada** [comment] 2023-10-06 09:30
Also get same crash for me. @rfresh2

**Comment by magcicada** [comment] 2023-10-06 09:45
The weird that after I restarted the game, the crash no longer happened.

**Comment by ghost** [comment] 2023-10-07 02:49
> The weird that after I restarted the game, the crash no longer happened.

It seems so.

**Comment by rfresh2** [comment] 2023-10-07 03:08
Should be fixed in https://github.com/rfresh2/XaeroPlus/releases/tag/Forge-1.12.2-151

**Closed as completed by rfresh2** 2023-10-07 03:08 UTC
